name: Cypress Tests CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Fazer o Checkout do Código
      - name: Checkout repository
        uses: actions/checkout@v4

      # Passo 2: Configurar o Ambiente Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      #Passo 3: Instalar Dependências
      - name: Install dependencies
        run: npm ci

      # Passo 4: Limpar relatórios antigos
      - name: Clean old reports
        run: npm run clean:reports

      # Passo 5: Executar Testes Cypress
      - name: Run Cypress Core Tests (Exclude Purchase & Order Mgmt) # Nome do passo atualizado
        uses: cypress-io/github-action@v6
        with:
          spec: cypress/integration/admin/features/{authentication,authorization,login,manage_product}.feature
          browser: chrome

      # Passo 6: Gerar o Relatório HTML Cucumber (Mesmo se os testes falharem)
      - name: Generate Cucumber HTML Report
        if: always()
        run: npm run cucumber:generate-html

      # Passo 7: Arquivar Artefatos (Relatórios, Vídeos, Screenshots)
      - name: Upload Cypress artifacts
        uses: actions/upload-artifact@v4
        # O passo de upload de artefatos deve ser executado mesmo que o teste falhe.
        if: always()
        with:
          name: cypress-execution-artifacts
          # Lista dos diretórios que incluiremos no artefato.
          path: |
            cypress/videos
            cypress/screenshots
            cypress/reports/cucumber/
          retention-days: 7
